export const LOADING_SOURCES = 'LOADING_SOURCES';
export const LOADING_NEWS_ITEMS = 'LOADING_NEWS_ITEMS';
export const LOADING_NEWS_ITEM = 'LOADING_NEWS_ITEM';

export const ERROR_LOADING_SOURCES = 'ERROR_LOADING_SOURCES';
export const ERROR_LOADING_NEWS_ITEMS = 'ERROR_LOADING_NEWS_ITEMS';
export const ERROR_LOADING_NEWS_ITEM = 'ERROR_LOADING_NEWS_ITEM';

export const RECEIVE_SOURCES = 'RECEIVE_SOURCES';
export const RECEIVE_NEWS_ITEMS = 'RECEIVE_NEWS_ITEMS';

export const TOGGLE_NEWS_AS_FAVORITE = 'TOGGLE_NEWS_AS_FAVORITE';
export const SET_FAVORITES_AS_CURRENT = 'SET_FAVORITES_AS_CURRENT';

export const SELECTED_SOURCE = 'SELECTED_SOURCE';

export const SELECTED_NEWS_ITEM = 'SELECTED_NEWS_ITEM';
